package com.iit.dashboard2022.ecu;

public final class ECUFaults {
    public static final String[] FAULTS = {
            "[ LOG ] MC0 Fault: Hardware Gate/Desaturation Fault",
            "[ LOG ] MC0 Fault: HW over-current Fault",
            "[ LOG ] MC0 Fault: Accelerator shorted",
            "[ LOG ] MC0 Fault: Accelerator Open",
            "[ LOG ] MC0 Fault: Current sensor Low",
            "[ LOG ] MC0 Fault: Current sensor High",
            "[ LOG ] MC0 Fault: Module Temperature Low",
            "[ LOG ] MC0 Fault: Module Temperature High",
            "[ LOG ] MC0 Fault: Control PCB Temperature Low",
            "[ LOG ] MC0 Fault: Control PCB Temperature High",
            "[ LOG ] MC0 Fault: Gate Dive PCB Temperature Low",
            "[ LOG ] MC0 Fault: Gate Dive PCB Temperature High",
            "[ LOG ] MC0 Fault: 5V Sense Voltage Low",
            "[ LOG ] MC0 Fault: 5V Sense Voltage High",
            "[ LOG ] MC0 Fault: 12V Sense Voltage Low",
            "[ LOG ] MC0 Fault: 12V Sense Voltage High",
            "[ LOG ] MC0 Fault: 2.5V Sense Voltage Low",
            "[ LOG ] MC0 Fault: 2.5V Sense Voltage High",
            "[ LOG ] MC0 Fault: 1.5V Sense Voltage Low",
            "[ LOG ] MC0 Fault: 2.5V Sense Voltage High",
            "[ LOG ] MC0 Fault: DC Bus Voltage High",
            "[ LOG ] MC0 Fault: DC Bus Voltage Low",
            "[ LOG ] MC0 Fault: Precharge Timeout",
            "[ LOG ] MC0 Fault: Precharge Voltage Failure",
            "[ LOG ] MC0 Fault: EEPROM Checksum Invalid",
            "[ LOG ] MC0 Fault: EEPROM Data Out of Range",
            "[ LOG ] MC0 Fault: EEPROM Update Required",
            "[ LOG ] MC0 Fault: Reserved",
            "[ LOG ] MC0 Fault: Reserved",
            "[ LOG ] MC0 Fault: Reserved",
            "[ LOG ] MC0 Fault: Brake Shorted",
            "[ LOG ] MC0 Fault: Brake Open",
            "[ LOG ] MC0 Fault: Motor Over-speed Fault",
            "[ LOG ] MC0 Fault: Over-current Fault",
            "[ LOG ] MC0 Fault: Over-voltage Fault",
            "[ LOG ] MC0 Fault: Inverter Over-temperature Fault",
            "[ LOG ] MC0 Fault: Accelerator Input Shorted Fault",
            "[ LOG ] MC0 Fault: Accelerator Input Open Fault",
            "[ LOG ] MC0 Fault: Direction Command Fault",
            "[ LOG ] MC0 Fault: Inverter Response Time-out Fault",
            "[ LOG ] MC0 Fault: Hardware Gate/Desaturation Fault_2",
            "[ LOG ] MC0 Fault: Hardware Over-current Fault_2",
            "[ LOG ] MC0 Fault: Under-voltage Fault",
            "[ LOG ] MC0 Fault: CAN Command Message Lost Fault",
            "[ LOG ] MC0 Fault: Motor Over-temperature Fault",
            "[ LOG ] MC0 Fault: Reserved",
            "[ LOG ] MC0 Fault: Reserved",
            "[ LOG ] MC0 Fault: Reserved",
            "[ LOG ] MC0 Fault: Brake Input Shorted Fault",
            "[ LOG ] MC0 Fault: Brake Input Open Fault",
            "[ LOG ] MC0 Fault: Module A Over-temperature Fault7",
            "[ LOG ] MC0 Fault: Module B Over-temperature Fault7",
            "[ LOG ] MC0 Fault: Module C Over-temperature Fault7",
            "[ LOG ] MC0 Fault: PCB Over-temperature Fault7",
            "[ LOG ] MC0 Fault: Gate Drive Board 1 Over-temperature Fault",
            "[ LOG ] MC0 Fault: Gate Drive Board 2 Over-temperature Fault7",
            "[ LOG ] MC0 Fault: Gate Drive Board 3 Over-temperature Fault7",
            "[ LOG ] MC0 Fault: Current Sensor Fault",
            "[ LOG ] MC0 Fault: Reserved",
            "[ LOG ] MC0 Fault: Reserved",
            "[ LOG ] MC0 Fault: Reserved",
            "[ LOG ] MC0 Fault: Reserved",
            "[ LOG ] MC0 Fault: Resolver Not Connected",
            "[ LOG ] MC0 Fault: Inverter Discharge Active",
            "[ LOG ] MC1 Fault: Hardware Gate/Desaturation Fault",
            "[ LOG ] MC1 Fault: HW over-current Fault",
            "[ LOG ] MC1 Fault: Accelerator shorted",
            "[ LOG ] MC1 Fault: Accelerator Open",
            "[ LOG ] MC1 Fault: Current sensor Low",
            "[ LOG ] MC1 Fault: Current sensor High",
            "[ LOG ] MC1 Fault: Module Temperature Low",
            "[ LOG ] MC1 Fault: Module Temperature High",
            "[ LOG ] MC1 Fault: Control PCB Temperature Low",
            "[ LOG ] MC1 Fault: Control PCB Temperature High",
            "[ LOG ] MC1 Fault: Gate Dive PCB Temperature Low",
            "[ LOG ] MC1 Fault: Gate Dive PCB Temperature High",
            "[ LOG ] MC1 Fault: 5V Sense Voltage Low",
            "[ LOG ] MC1 Fault: 5V Sense Voltage High",
            "[ LOG ] MC1 Fault: 12V Sense Voltage Low",
            "[ LOG ] MC1 Fault: 12V Sense Voltage High",
            "[ LOG ] MC1 Fault: 2.5V Sense Voltage Low",
            "[ LOG ] MC1 Fault: 2.5V Sense Voltage High",
            "[ LOG ] MC1 Fault: 1.5V Sense Voltage Low",
            "[ LOG ] MC1 Fault: 2.5V Sense Voltage High",
            "[ LOG ] MC1 Fault: DC Bus Voltage High",
            "[ LOG ] MC1 Fault: DC Bus Voltage Low",
            "[ LOG ] MC1 Fault: Precharge Timeout",
            "[ LOG ] MC1 Fault: Precharge Voltage Failure",
            "[ LOG ] MC1 Fault: EEPROM Checksum Invalid",
            "[ LOG ] MC1 Fault: EEPROM Data Out of Range",
            "[ LOG ] MC1 Fault: EEPROM Update Required",
            "[ LOG ] MC1 Fault: Reserved",
            "[ LOG ] MC1 Fault: Reserved",
            "[ LOG ] MC1 Fault: Reserved",
            "[ LOG ] MC1 Fault: Brake Shorted",
            "[ LOG ] MC1 Fault: Brake Open",
            "[ LOG ] MC1 Fault: Motor Over-speed Fault",
            "[ LOG ] MC1 Fault: Over-current Fault",
            "[ LOG ] MC1 Fault: Over-voltage Fault",
            "[ LOG ] MC1 Fault: Inverter Over-temperature Fault",
            "[ LOG ] MC1 Fault: Accelerator Input Shorted Fault",
            "[ LOG ] MC1 Fault: Accelerator Input Open Fault",
            "[ LOG ] MC1 Fault: Direction Command Fault",
            "[ LOG ] MC1 Fault: Inverter Response Time-out Fault",
            "[ LOG ] MC1 Fault: Hardware Gate/Desaturation Fault_2",
            "[ LOG ] MC1 Fault: Hardware Over-current Fault_2",
            "[ LOG ] MC1 Fault: Under-voltage Fault",
            "[ LOG ] MC1 Fault: CAN Command Message Lost Fault",
            "[ LOG ] MC1 Fault: Motor Over-temperature Fault",
            "[ LOG ] MC1 Fault: Reserved",
            "[ LOG ] MC1 Fault: Reserved",
            "[ LOG ] MC1 Fault: Reserved",
            "[ LOG ] MC1 Fault: Brake Input Shorted Fault",
            "[ LOG ] MC1 Fault: Brake Input Open Fault",
            "[ LOG ] MC1 Fault: Module A Over-temperature Fault7",
            "[ LOG ] MC1 Fault: Module B Over-temperature Fault7",
            "[ LOG ] MC1 Fault: Module C Over-temperature Fault7",
            "[ LOG ] MC1 Fault: PCB Over-temperature Fault7",
            "[ LOG ] MC1 Fault: Gate Drive Board 1 Over-temperature Fault",
            "[ LOG ] MC1 Fault: Gate Drive Board 2 Over-temperature Fault7",
            "[ LOG ] MC1 Fault: Gate Drive Board 3 Over-temperature Fault7",
            "[ LOG ] MC1 Fault: Current Sensor Fault",
            "[ LOG ] MC1 Fault: Reserved",
            "[ LOG ] MC1 Fault: Reserved",
            "[ LOG ] MC1 Fault: Reserved",
            "[ LOG ] MC1 Fault: Reserved",
            "[ LOG ] MC1 Fault: Resolver Not Connected",
            "[ LOG ] MC1 Fault: Inverter Discharge Active",
    };
}
